### PR TITLE
Updated and Improved

### PR DESCRIPTION
**Pull request by fheilz**
-Fixed some of the problems in the code
-Updated README to make it more beginner friendly
-Changed Rate Limits so that you don't get banned with the default ones.
-Added helpful links
-Added more keywords

### CODE REVIEW

**Review by kurozael — APPROVED** [review]
This is great, thanks very much for your contribution.

**Comment by fheilz** [comment]
I'm working on a few more updates do you have a todo or stuff that I should add?

**Comment by kurozael** [comment]
Hi @LiquidPrototype! Not at this time, really, I'm sort of out of ideas, but please do improve this where you can it has gained a lot of attention. I guess a Contributors section would be good as well 👍

**Comment by pbartett** [comment]
What would be handy is Ability to add negative keywords or blocked users

**Pull request merged**
